### ISSUE TITLE
Enter key in password input defaults to "Show password" over "Login"

### ISSUE THREAD

**Issue by legrab** [dmitry-lapin/restaurant_pos#2]
Having entered the password in the login screen, the usual behavior of the 'enter' key is logging into the website, but it is triggering the "show password" functionality instead that leads to undesired leaking of confidential user data.

**Steps to reproduce:**
- Select the password input field and input any text then hit enter.

**Severity:**
- High - security perspective

**Comment by dmitry-lapin** [comment]
Thank you @legrab, the problem has been solved.
